services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  dev:
    build:
      context: .
      dockerfile: FlexyBox.dev/Dockerfile
    environment:
      - SQLConnectionString__ConnectionString=Server=sqlserver,1433;Database=FlexyBoxDB;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True
    entrypoint: ["bash", "-c"]
    command: >
      "dotnet tool restore &&
       dotnet ef database update --project FlexyBox.dev"
    depends_on:
      - sqlserver
    networks:
      - app-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"  
      - "10001:10001"  
      - "10002:10002"  
    volumes:
      - ./azurite:/data  
    command: "azurite -s --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    networks:
      - app-network
    depends_on:
     - dev

  api:
    image: ${DOCKER_REGISTRY-}flexyboxapi
    build:
      context: .
      dockerfile: FlexyBox.api/Dockerfile
    depends_on:
      - sqlserver
      - azurite
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - SQLConnectionString__ConnectionString=Server=sqlserver,1433;Database=FlexyBoxDB;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True
      - StorageConnectionString__ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFe3fS4rZF8D58a5w==;BlobEndpoint=http://localhost:10000/devstoreaccount1;QueueEndpoint=http://localhost:10001/devstoreaccount1;TableEndpoint=http://localhost:10002/devstoreaccount1;
      - Okta__Authority=https://dev-uct7p4or1fa0cwym.us.auth0.com/
      - Okta__Audience=https://localhost:7204/
    ports:
      - "7132:8080"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

