services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  dev:
    build:
      context: .
      dockerfile: FlexyBox.dev/Dockerfile
    environment:
      - SQLConnectionString__ConnectionString=Server=sqlserver,1433;Database=FlexyBoxDB;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True
    entrypoint: ["bash", "-c"]
    command: >
      "dotnet tool restore &&
       dotnet ef database update --project FlexyBox.dev"
    depends_on:
      - sqlserver
    networks:
      - app-network

  # azurite:
  #   container_name: azurite
  #   image: mcr.microsoft.com/azure-storage/azurite
  #   restart: always
  #   volumes:
  #      - azurite_data:/data
  #   command: azurite --loose -l /data --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0
  #   ports:
  #      - '10000:10000'
  #      - '10001:10001'
  #      - '10002:10002'

  api:
    image: ${DOCKER_REGISTRY-}flexyboxapi
    build:
      context: .
      dockerfile: FlexyBox.api/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cert.pfx
      - ASPNETCORE_URLS=https://+:443;http://+:8080
      - SQLConnectionString__ConnectionString=Server=sqlserver,1433;Database=FlexyBoxDB;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True
      - StorageConnectionString__ConnectionString=***;
      - OktaServer__Authority=https://dev-uct7p4or1fa0cwym.us.auth0.com/
      - OktaServer__Audience=https://localhost:7204/
    ports:
      - "7203:8080"
      - "7204:443"
    volumes:
      - ./cert.pfx:/app/cert.pfx   # Certificates
      - ./content:/app/content      # Volume for storing files and images
    networks:
      - app-network

    
  web:
    build:
      context: .
      dockerfile: FlexyBox.web/Dockerfile
    ports:
    - "7125:80"  
    - "443:443"  
    volumes:
      - ./FlexyBox.web/nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/ssl/certs/cert.pem
      - ./key.pem:/etc/ssl/private/key.pem
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
     - api
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
